# syntax=docker/dockerfile:1

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG BASE_IMAGE
ARG BUILD_PATH
ARG CY
ARG OPENUSD_VERSION
ARG MATERIALX_VERSION
ARG SOURCE_REVISION
ARG SOURCE_SHA256
ARG SCRIPT_SHA256
ARG EXPECTED_GCC_MAJOR
ARG INSTALL_PREFIX
ARG BUILD_JOBS=4
ARG ASWF_SOURCE_COMMIT
ARG WORKFLOW_REVISION
ARG SOURCE_REPOSITORY=https://github.com/PixarAnimationStudios/OpenUSD

COPY build_openusd_path_image.sh /opt/openusd-matrix/build_openusd_path_image.sh
COPY aswf-build_usd.sh /opt/openusd-matrix/aswf-build_usd.sh

RUN chmod 0755 \
      /opt/openusd-matrix/build_openusd_path_image.sh \
      /opt/openusd-matrix/aswf-build_usd.sh \
    && /opt/openusd-matrix/build_openusd_path_image.sh build

ENV OPENUSD_MATRIX_BUILD_PATH=${BUILD_PATH} \
    OPENUSD_MATRIX_CY=${CY} \
    OPENUSD_MATRIX_PREFIX=${INSTALL_PREFIX} \
    PATH=${INSTALL_PREFIX}/bin:${PATH} \
    PYTHONPATH=${INSTALL_PREFIX}/lib/python \
    LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib \
    PXR_PLUGINPATH_NAME=${INSTALL_PREFIX}/plugin/usd \
    PXR_MTLX_STDLIB_SEARCH_PATHS=${INSTALL_PREFIX}/share/MaterialX

LABEL org.opencontainers.image.source="https://github.com/nicolaspopravka/aswf-docker" \
      org.opencontainers.image.revision="${WORKFLOW_REVISION}" \
      org.opencontainers.image.title="OpenUSD build-path matrix ${BUILD_PATH} CY${CY}" \
      io.openusd-matrix.build-path="${BUILD_PATH}" \
      io.openusd-matrix.cy="${CY}" \
      io.openusd-matrix.openusd-version="${OPENUSD_VERSION}" \
      io.openusd-matrix.materialx-version="${MATERIALX_VERSION}" \
      io.openusd-matrix.base-image="${BASE_IMAGE}" \
      io.openusd-matrix.source-repository="${SOURCE_REPOSITORY}" \
      io.openusd-matrix.source-revision="${SOURCE_REVISION}" \
      io.openusd-matrix.source-sha256="${SOURCE_SHA256}" \
      io.openusd-matrix.script-sha256="${SCRIPT_SHA256}" \
      io.openusd-matrix.aswf-source-commit="${ASWF_SOURCE_COMMIT}" \
      io.openusd-matrix.install-prefix="${INSTALL_PREFIX}"
