#!/usr/bin/env bash
set -eu
cmake -S /cycles -B /tmp/issue50-cycles-build \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/tmp/issue50-install \
  -DCMAKE_PREFIX_PATH=/usr/local -DPXR_ROOT=/usr/local \
  -DPython3_INCLUDE_DIR=/usr/local/include/python3.13 \
  -DPython3_LIBRARY=/usr/local/lib/libpython3.13.so \
  -DCMAKE_MODULE_PATH=/modules \
  -DCMAKE_PROJECT_INCLUDE=/evidence/import_opengl.cmake \
  -DWITH_LIBS_PRECOMPILED=OFF -DWITH_CYCLES_OSL=OFF \
  -DWITH_CYCLES_OPENVDB=OFF -DWITH_CYCLES_NANOVDB=OFF \
  -DWITH_CYCLES_OPENIMAGEDENOISE=OFF -DWITH_CYCLES_ALEMBIC=OFF \
  -DWITH_CYCLES_LOGGING=OFF -DWITH_CYCLES_DEVICE_ONEAPI=OFF \
  -DWITH_CYCLES_ONEAPI_BINARIES=OFF -DWITH_CYCLES_DEVICE_CUDA=OFF \
  -DWITH_CYCLES_CUDA_BINARIES=OFF -DWITH_CYCLES_DEVICE_HIP=OFF \
  -DWITH_CYCLES_DEVICE_HIPRT=OFF -DWITH_CYCLES_HIP_BINARIES=OFF \
  -DWITH_CYCLES_DEVICE_METAL=OFF -DWITH_CYCLES_DEVICE_OPTIX=OFF
